In [ ]:
!pip install nltk
#natural language tool kit

In [ ]:
paragraph = '''Narendra Damodardas Modi was born on 17 September 1950 to a Gujarati family of Other Backward Class (OBC) background and Hindu faith[13][14] in Vadnagar, Mehsana district, Bombay State (present-day Gujarat). He was the third of six children born to Damodardas Mulchand Modi (c. 1915–1989) and Hiraben Modi (1923–2022).[15][h][16] According to Modi and his neighbours, he worked infrequently in his father's tea stall in the Vadnagar railway station.[17][18][19]

Modi completed his higher secondary education in Vadnagar in 1967; his teachers described him as an average student and a keen, gifted debater with an interest in theatre.[20] He preferred playing larger-than-life characters in theatrical productions, which has influenced his political image.[21][22]
'''

In [ ]:
paragraph

"Narendra Damodardas Modi was born on 17 September 1950 to a Gujarati family of Other Backward Class (OBC) background and Hindu faith[13][14] in Vadnagar, Mehsana district, Bombay State (present-day Gujarat). He was the third of six children born to Damodardas Mulchand Modi (c.\u20091915–1989) and Hiraben Modi (1923–2022).[15][h][16] According to Modi and his neighbours, he worked infrequently in his father's tea stall in the Vadnagar railway station.[17][18][19]\n\nModi completed his higher secondary education in Vadnagar in 1967; his teachers described him as an average student and a keen, gifted debater with an interest in theatre.[20] He preferred playing larger-than-life characters in theatrical productions, which has influenced his political image.[21][22]\n"

In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#tokenization- convert paragraph -> sentences -> words
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
sentences = nltk.sent_tokenize(paragraph) #converts paragraph into sentences
sentences

['Narendra Damodardas Modi was born on 17 September 1950 to a Gujarati family of Other Backward Class (OBC) background and Hindu faith[13][14] in Vadnagar, Mehsana district, Bombay State (present-day Gujarat).',
 'He was the third of six children born to Damodardas Mulchand Modi (c.\u20091915–1989) and Hiraben Modi (1923–2022).',
 "[15][h][16] According to Modi and his neighbours, he worked infrequently in his father's tea stall in the Vadnagar railway station.",
 '[17][18][19]\n\nModi completed his higher secondary education in Vadnagar in 1967; his teachers described him as an average student and a keen, gifted debater with an interest in theatre.',
 '[20] He preferred playing larger-than-life characters in theatrical productions, which has influenced his political image.',
 '[21][22]']

In [ ]:
#stemming
stemmer = PorterStemmer()
stemmer.stem('hisotry')

'hisotri'

In [ ]:
#lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize('history')

[nltk_data] Downloading package wordnet to /root/nltk_data...


'history'

In [ ]:
#lets clean the data, and remove everything except a-ZA-Z
#lower the case
import re
corpus = []
for sentence in sentences:
  sentence = re.sub('[^a-zA-Z]',' ',sentence)
  corpus.append(sentence.lower())
corpus

['narendra damodardas modi was born on    september      to a gujarati family of other backward class  obc  background and hindu faith         in vadnagar  mehsana district  bombay state  present day gujarat  ',
 'he was the third of six children born to damodardas mulchand modi  c             and hiraben modi             ',
 '     h      according to modi and his neighbours  he worked infrequently in his father s tea stall in the vadnagar railway station ',
 '              modi completed his higher secondary education in vadnagar in       his teachers described him as an average student and a keen  gifted debater with an interest in theatre ',
 '     he preferred playing larger than life characters in theatrical productions  which has influenced his political image ',
 '        ']

In [ ]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
len(corpus)

6

In [ ]:
#Apply stemming
corpus_final = []
for i in corpus:
  #convert sentences into words
  words = nltk.word_tokenize(i)
  temp = []
  for word in words:
    if word not in set(stopwords.words('english')):
      # print(stemmer.stem(word))
      temp.append(lemmatizer.lemmatize(word))
  corpus_final.append(' '.join(temp))
corpus_final

['narendra damodardas modi born september gujarati family backward class obc background hindu faith vadnagar mehsana district bombay state present day gujarat',
 'third six child born damodardas mulchand modi c hiraben modi',
 'h according modi neighbour worked infrequently father tea stall vadnagar railway station',
 'modi completed higher secondary education vadnagar teacher described average student keen gifted debater interest theatre',
 'preferred playing larger life character theatrical production influenced political image',
 '']

In [ ]:
#bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True)
x = cv.fit_transform(corpus_final)

In [ ]:
cv.vocabulary_

{'narendra': 35,
 'damodardas': 10,
 'modi': 33,
 'born': 5,
 'september': 45,
 'gujarati': 21,
 'family': 17,
 'backward': 3,
 'class': 8,
 'obc': 37,
 'background': 2,
 'hindu': 23,
 'faith': 16,
 'vadnagar': 56,
 'mehsana': 32,
 'district': 14,
 'bombay': 4,
 'state': 48,
 'present': 41,
 'day': 11,
 'gujarat': 20,
 'third': 55,
 'six': 46,
 'child': 7,
 'mulchand': 34,
 'hiraben': 24,
 'according': 0,
 'neighbour': 36,
 'worked': 57,
 'infrequently': 27,
 'father': 18,
 'tea': 51,
 'stall': 47,
 'railway': 43,
 'station': 49,
 'completed': 9,
 'higher': 22,
 'secondary': 44,
 'education': 15,
 'teacher': 52,
 'described': 13,
 'average': 1,
 'student': 50,
 'keen': 29,
 'gifted': 19,
 'debater': 12,
 'interest': 28,
 'theatre': 53,
 'preferred': 40,
 'playing': 38,
 'larger': 30,
 'life': 31,
 'character': 6,
 'theatrical': 54,
 'production': 42,
 'influenced': 26,
 'political': 39,
 'image': 25}

In [ ]:
#this is for first sentence in corpus
print(corpus[0])
x[0].toarray()

narendra damodardas modi was born on    september      to a gujarati family of other backward class  obc  background and hindu faith         in vadnagar  mehsana district  bombay state  present day gujarat  


array([[0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
#tf-idf
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(ngram_range=(1,3), max_features =30)
#max features gives top 30 highest frequency words in the features
y = tf.fit_transform(corpus_final)
y

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 37 stored elements and shape (6, 30)>

In [ ]:
y[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.25669648,
        0.25669648, 0.25669648, 0.25669648, 0.25669648, 0.25669648,
        0.25669648, 0.25669648, 0.21049479, 0.        , 0.        ,
        0.25669648, 0.25669648, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.25669648, 0.25669648,
        0.25669648, 0.        , 0.21049479, 0.15228753, 0.17771416]])

In [1]:
#word 2 vec
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 20.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 25.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 13.0 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.1
    Uninstalling scipy-1.16.1:
      Successfully uninstalled scipy-1.16.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requir

In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [2]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')
#we will have 300 feature representation

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [3]:
vec_king = wv['king']
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [4]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [5]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [8]:
wv.similarity("cricket", "sports")

0.40087253

In [11]:
vec = wv['king'] - wv['man'] + wv['women']

In [12]:
wv.most_similar([vec])

[('king', 0.6478992700576782),
 ('queen', 0.535493791103363),
 ('women', 0.5233659148216248),
 ('kings', 0.5162314772605896),
 ('queens', 0.4995364248752594),
 ('kumaris', 0.49238473176956177),
 ('princes', 0.46233269572257996),
 ('monarch', 0.45280295610427856),
 ('monarchy', 0.4293173849582672),
 ('kings_princes', 0.42342400550842285)]